spring.data.mongodb.uri=mongodb+srv://Malini:0105@cluster0.bco7ekv.mongodb.net/newsletter_test

app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.expiration-ms=86400000

logging.level.com.newsletter=WARN
logging.level.org.springframework.data.mongodb=WARN
